name: Follow-N-Star-Action

on:
  schedule:
    - cron: '0 12 * * *'    # run @12pm every day
  workflow_dispatch:        # allow manual deployments

jobs:
  build:
    runs-on: ubuntu-latest  # use linux environment
    steps:

      - name: Checkout
        uses: actions/checkout@v5.0.0       # check-out repository

      - name: Setup Python
        uses: actions/setup-python@v6.0.0   # install python version
        with:
          python-version: '3.13'

      - name: Install Packages  # install pip & requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Create .env file  # create .env file & append variable secrets
        run: |
          touch .env
          echo PERSONAL_USERNAME=${{ secrets.PERSONAL_USERNAME }} >> .env
          echo PERSONAL_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} >> .env

      - name: Execute Main      # run main python script
        run: python main.py

      - name: Commit Changes    # commit changes to repo as action
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "update EXPLORED_LOGINS file" --allow-empty)

      - name: Push Changes      # push changes to repo as action
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     # allow read/write access for action
          branch: main